# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d13cdba95a9232f29bcff56f6fecd77da16089962a65b08178a703938414331c36fb52ea05e5a723f1a51bb6946bd6a08998c7a7f44042d31ba567086fa6674

test:
  secret_key_base: 8b90785a784537399d23b6d8c369aa4ee594365dee5a0cce8883c230093a2c1ab4004ac6ec2532ee7fd0787402f9fddf1b3ee283cbc62029af7e2f3b9bab738f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
